
- hosts: localhost
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        api_version: v1
        name: boruta-developers
        kind: Namespace
        state: present

    - name: Create developers.boruta Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: boruta-developers-web
            namespace: boruta-developers
            labels:
              app: boruta-developers
          spec:
            selector:
              app: boruta-developers
            ports:
            - protocol: TCP
              targetPort: 80
              name: web-tcp
              port: 80

    - name: Create SSL let's encrypt certificate
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: Issuer
          metadata:
            name: letsencrypt-production
            namespace: boruta-developers
          spec:
            acme:
              email: io.pascal.knoth@gmail.com
              server: https://acme-v02.api.letsencrypt.org/directory
              privateKeySecretRef:
                name: boruta-developers-ssl-account-key
              solvers:
              - http01:
                  ingress:
                    class: nginx
                selector:
                  dnsZones:
                  - 'developers.boruta.patatoid.fr'

    - name: Create developers.boruta Ingress
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: main-ingress
            namespace: boruta-developers
            annotations:
              cert-manager.io/issuer: letsencrypt-production
              kubernetes.io/ingress.class: "nginx"
            #   nginx.ingress.kubernetes.io/rewrite-target: /
          spec:
            rules:
            - host: developers.boruta.patatoid.fr
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: boruta-developers-web
                      port:
                        number: 80
            tls:
              - hosts:
                - developers.boruta.patatoid.fr
                secretName: boruta-developers-cert

    - name: Create developers.boruta deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: boruta-developers
            namespace: boruta-developers
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: boruta-developers
            template:
              metadata:
                name: boruta-developers
                labels:
                  app: boruta-developers
              spec:
                containers:
                  - image: "ghcr.io/malach-it/developers.boruta:{{ release_tag }}"
                    readinessProbe:
                      httpGet:
                        path: /
                        port: 80
                    imagePullPolicy: Always
                    name: boruta-developers
                imagePullSecrets:
                - name: dockerconfigjson-github-com
